#!/usr/bin/env bash

PROGRAM=quad-light

# Update the brightness based on any button clicks/scrolls.
case "$BLOCK_BUTTON" in
  4) $PROGRAM -A 10;;
  5) $PROGRAM -U 10;;
esac

# Get the current brightness and round to the nearest 10.
VALUE="$($PROGRAM -G | xargs printf '%.0f')"
VALUE="$(( 10 * ((VALUE + 2) / 10) ))"

# Get the previous brightness value and save the current value.
TMP_FILE="/tmp/i3blocks.brightness"
declare -i PREV_VALUE
read PREV_VALUE < $TMP_FILE
if [ -z "$PREV_VALUE" ] || [ "$VALUE" -ne "$PREV_VALUE" ]; then
  echo "$VALUE" > "$TMP_FILE"
fi

# Set color if the brightness has changed recently.
COLOR=""
ELAPSED="$(expr $(date +%s) - $(date +%s -r $TMP_FILE))"
if [ "$ELAPSED" -le 5 ]; then
  COLOR=$(xgetres i3blocks.Brightness.modified)
fi

ICON="" # fa-sun

# Font Awesome 5 does not include the space character and Pango seems to have
# trouble falling back to a different font without this.
PANGO_SPACE="<span fallback='true'> </span>"

echo "$ICON$PANGO_SPACE$VALUE%"
echo
echo "$COLOR"
