#!/bin/sh
load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

color=""
loaded=$(bc <<< "$load>$cpus")
if [ "$loaded" == "1" ]; then
    color="#b8bb26"
fi

echo "$load"
echo "$load"
echo "$color"
