#!/usr/bin/env bash

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

color=""
loaded=$(bc <<< "$load>$cpus")
if [ "$loaded" == "1" ]; then
  color=$(xgetres i3blocks.Load.high)
fi

ICON="" # fa-chart-area

# Font Awesome 5 does not include the space character and Pango seems to have
# trouble falling back to a different font without this.
PANGO_SPACE="<span fallback='true'> </span>"

echo "$ICON$PANGO_SPACE$load"
echo
echo "$color"
