#!/usr/bin/env bash


num_updates=$(checkupdates | wc -l)
case $num_updates in
	0) exit 0 ;;
	1) update_str="1 Update" ;;
	*) update_str="$num_updates Updates" ;;
esac

ICON="" # fa-download

# Font Awesome 5 does not include the space character and Pango seems to have
# trouble falling back to a different font without this.
PANGO_SPACE="<span fallback='true'> </span>"

echo "$ICON$PANGO_SPACE$update_str"
