#!/usr/bin/env bash

SINK=$BLOCK_INSTANCE

# Set the volume based on any button clicks/scrolls.
case "$BLOCK_BUTTON" in
  1) pactl set-sink-mute $SINK toggle;;
  4) pactl set-sink-volume $SINK +5%;;
  5) pactl set-sink-volume $SINK -5%;;
esac

# Get the mute status.
MUTE="$(pactl list sinks \
	| grep -m $((SINK + 1)) "^\s*Mute" \
	| tail -n 1 |  sed -r 's/.*Mute:\s(.*)$/\1/')"

# Get the current volume.
VOLUME="$(pactl list sinks \
	| grep -m $((SINK + 1)) "^\s*Volume" \
	| tail -n 1 |  sed -r 's/.*\s([0-9]+)%\s.*$/\1/')"

# If the volume is above 100% then reset it.
if [ "$VOLUME" -gt 100 ]; then
  pactl set-sink-volume "$SINK" 100%
  VOLUME=100
fi

# Get the previous volume and mute
TMP_FILE="/tmp/i3blocks.volume"
declare -i PREV_VOLUME
read PREV_MUTE PREV_VOLUME < $TMP_FILE
if [ -z "$PREV_MUTE" ] || [ -z "$PREV_VOLUME" ] || [ "$MUTE" != "$PREV_MUTE" ] || [ "$VOLUME" -ne "$PREV_VOLUME" ]; then
  echo "$MUTE $VOLUME" > "$TMP_FILE"
fi

COLOR=""
ELAPSED="$(expr $(date +%s) - $(date +%s -r $TMP_FILE))"
if [ "$ELAPSED" -le 5 ]; then
  COLOR=$(xgetres i3blocks.Volume.modified)
fi

ICON_NORMAL="" # fa-volume-up
ICON_MUTE=""   # fa-volume-off

# Font Awesome 5 does not include the space character and Pango seems to have
# trouble falling back to a different font without this.
PANGO_SPACE="<span fallback='true'> </span>"

case "$MUTE" in
  yes) echo "$ICON_MUTE$PANGO_SPACE$VOLUME%";;
  no) echo "$ICON_NORMAL$PANGO_SPACE$VOLUME%";;
esac

echo
echo "$COLOR"
