#!/usr/bin/env bash

if [[ -z "$BLOCK_INSTANCE" ]]; then
  echo "Missing required interface"
  exit 0
fi

# interface IEEE 802.11  ESSID:"NNN"
#           Mode:Managed  Frequency:5.745 GHz  Access Point: XX:XX:XX:XX:XX:XX
#           Bit Rate=XX.X Mb/s   Tx-Power=XX dBm
#           Retry short limit:X   RTS thr:off   Fragment thr:off
#           Power Management:on
#           Link Quality=XX/70  Signal level=-XX dBm
#           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
#           Tx excessive retries:0  Invalid misc:0   Missed beacon:0
config=$(iwconfig $BLOCK_INSTANCE)

# If there is no power then assume the interface is off.
power=$(echo $config | sed -nr 's/.*Tx-Power=([0-9]*).*/\1/p')
if [[ -z "$power" ]]; then
  exit 0
fi

# If there is no ssid then assume there is no connection (iwgetid is a
# convenient method for getting the SSID from iwconfig).
ssid=$(iwgetid -r $BLOCK_INSTANCE)
if [[ -z "$ssid" ]]; then
  echo "×"
  exit 0
fi

# Scale the link quality from [0-100].
signal=$(echo $config | sed -nr 's/.*Link\sQuality=([0-9\/]*).*/100*\1/p' | bc)

ICON="" # fa-wifi

# Font Awesome 5 does not include the space character and Pango seems to have
# trouble falling back to a different font without this.
PANGO_SPACE="<span fallback='true'> </span>"

echo "$ICON$PANGO_SPACE$ssid ($signal%)"
