#!/bin/bash

# Update the brightness based on any button clicks/scrolls.
case "$BLOCK_BUTTON" in
  4) light -A 10;;
  5) light -U 10;;
esac

# Get the current brightness and round to the nearest 10.
VALUE="$(light -G | xargs printf '%.0f')"
VALUE="$(( 10 * ((VALUE + 2) / 10) ))"

# Get the previous brightness value and save the current value.
TMP_FILE="/tmp/i3blocks.brightness"
read PREV_VALUE < $TMP_FILE
if [ "$VALUE" -ne "$PREV_VALUE" ]; then
  echo "$VALUE" > "$TMP_FILE"
fi

# Set color if the brightness has changed recently.
COLOR="#839496"
ELAPSED="$(expr $(date +%s) - $(date +%s -r $TMP_FILE))"
if [ "$ELAPSED" -le 5 ]; then
  COLOR="#b58900"
fi

echo " $VALUE%"
echo "$VALUE%"
echo "$COLOR"
