#!/usr/bin/env bash

wifi_state=$(nmcli radio wifi)
if [[ "$wifi_state" == "disabled" ]]; then
  exit 0
fi

active_network=$(nmcli --fields SSID,SIGNAL,ACTIVE device wifi list | grep yes)
if [[ -z "$active_network" ]]; then
  echo "×"
  exit 33
fi

ssid=$(echo $active_network | cut -d ' ' -f 1)
signal=$(echo $active_network | cut -d ' ' -f 2)

echo "$ssid ($signal%)"
echo "$signal%"
