#!/bin/sh
load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

color="#839496"
loaded=$(bc <<< "$load>$cpus")
if [ "$loaded" == "1" ]; then
    color="#d33682"
fi

echo "$load"
echo "$load"
echo "$color"
