#!/bin/sh
load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

color="#928374"
loaded=$(bc <<< "$load>$cpus")
if [ "$loaded" == "1" ]; then
    color="#b16286"
fi

echo "$load"
echo "$load"
echo "$color"
